### ISSUE TITLE
If the command fail, double check that the python version still matches. If not, please let us know by opening an issue.

### ISSUE THREAD

**Issue by gerdesj** [kamax-io/matrix-synapse-rest-auth#11]
Python 3.6 for Ubuntu 18.04.2 LTS (Bionic Beaver)

**Comment by maxidorius** [comment]
Seems like our wording wasn't really appropriate :)
Could you give us:
- The command + full output
- `ls -l` on The path under which synapse is installed

**Comment by gerdesj** [comment]
Sorry, I was a little cryptic.  The command worked fine when I changed 5 to 6.  On that Ubuntu box (current LTS) Python is 3.6.

**Comment by maxidorius** [comment]
Which version of synapse do you have?

**Comment by gerdesj** [comment]
```
# apt-cache policy matrix-synapse-py3
matrix-synapse-py3:
  Installed: 1.0.0+bionic1

```
I use mxisd to connect to AD and it works very nicely.  It was a bit of a challenge but your docs are very good

**Comment by maxidorius** [comment]
We will not maintaining the project going forward. Thank you for considering it.
