### ISSUE TITLE
enforceLowercase Appears not to work?

### ISSUE THREAD

**Issue by Iratu** [kamax-io/matrix-synapse-rest-auth#4]
Good day, I've tried to get this system to work with my existing website but I'm running into the issue where I can't have a username with a capital letter, I'd like to be able to have my users not worry about Capital letters in their names.

I'm getting the following error when I set it to False.
`Error: Problem communicating with the given homeserver. (M_INVALID_USERNAME)`

and If I set it to True I'm getting the Invalid Username/password instantly.

Both settings don't even try to communicate with my PHP file that does the username/password check, I can login just fine if I only use lowercase letters.

I'm running this on a freshly installed Debian 9 install with the latest Matrix-Synapse and latest Riot.

**Comment by Iratu** [comment]
I see, so there's no way to make Matrix think that the user used a Lowercase login while actually using a Capital letters.

Would it be possible to authenticate by using an email address, which would probably solve my issue faster since those have to be lowercase anyway.

**Comment by maxidor** [comment]
> there's no way to make Matrix think that the user used a Lowercase login while actually using a Capital letters.

Matrix (the protocol) only allows lowercase in the User ID. Implementations are free to handle users attempting to login with upper case how they see fit. It's simply something that needs to be handled in the client/server (or not handled). In this case, we could call it poor UX from Riot and synapse.

> Would it be possible to authenticate by using an email address, which would probably solve my issue faster since those have to be lowercase anyway.

This is out of scope of this component, but Email addresses get turned to Matrix User IDs for the actual login, so if the username contains upper case still, it will fail all the same. Whatever REST endpoint this component talks to needs to return a lowercase username. If your Identity store is case insensitive for searches, you could do the lowering yourself?

**Comment by Iratu** [comment]
I've decided to not worry about this and will keep it like this for now, perhaps we'll add a small script to Riot to force lowercase but that'll be something for later.

Quick different question, how would I give myself Administrator or am I forced to create at least one regular Matrix user?

**Comment by maxidor** [comment]
> How would I give myself Administrator or am I forced to create at least one regular Matrix user?

If you mean Administrator at synapse level, this is not supported. I don't even know if a password provider is able to do it. At this point, it's editing the DB directly. A synapse administrator is a regular Matrix User, with a flag in the database and has access to some extra API. You don't get any extra priviledges at the rooms level.

**Comment by Iratu** [comment]
Thanks for your help, I kinda want a closed off community so I have Room creation to be Admin only which I can now do 👍
