### ISSUE TITLE
request: matrix-synapse-rest-auth package on pypi

### ISSUE THREAD

**Issue by tgurr** [kamax-io/matrix-synapse-rest-auth#5]
It would be nice if we could have this python module available on pypi so distributions could easily provide a package for. Like there is for e.g. https://pypi.org/project/matrix-synapse-ldap3. Manually installing Python modules in /usr/lib/pythonX.X/dist-packages is a bad thing as things change, Python 2 -> 3, Python 3.5 -> 3.6 -> 3.7.

**Comment by maxidorius** [comment]
@tgurr I'm not familiar at all with the python ecosystem. Are there resources/guides you would recommend that would allow this to be better integrated with the ecosystem? Thanks!

**Comment by tgurr** [comment]
@maxidorius Sorry me neither, so I'm afraid I can't give you any advice here. I'm mainly just a distribution packager and synapse/matrix/mxsid user.

**Comment by maxidorius** [comment]
No problem, I'll keep an eye on this and hopefully some people can help me get more info. Thank you for bringing my attention to this!

**Comment by maxidorius** [comment]
We will not maintaining the project going forward. Thank you for considering it.
